### ISSUE TITLE
Casos
de Uso de Gestión Perfiles Sistema

### ISSUE THREAD

**Issue by abrahamfrayde** [abrahamfrayde/appswamid#11]

**Comment by evecanche** [comment]
![Casos de uso Perfiles.png](https://zube.io/files/abrahamfrayde/5ddbd3cf674ab160e50100fc39bddec6.png)

**Comment by evecanche** [comment]
Gestión de Perfiles del sistema +1:

**Comment by F3NYX-MX** [comment]
ok
