### ISSUE TITLE
Diagrama
de Clases

### ISSUE THREAD

**Issue by abrahamfrayde** [abrahamfrayde/appswamid#15]

**Comment by tony130675** [comment]
![SGS - MID - Clases.jpg](https://zube.io/files/abrahamfrayde/88d1a0b2f921b2937e6bec3bab350670.jpeg)

**Comment by tony130675** [comment]
Me pueden apoyar para verificar si están todas las tablas y con todos sus campos, así como sus relaciones y cardinalidades por favor?

Cualquier ajuste me dicen

Gracias!

**Comment by tony130675** [comment]
![SGS - MID - Clases V2.jpg](https://zube.io/files/abrahamfrayde/921dbbecfc2fe8263c8cc1e76667c6d4.jpeg)

**Comment by tony130675** [comment]
Versión 2.0 del Diagrama de Clases, por favor que lo revisen.

Gracias!

**Comment by tony130675** [comment]
Cambie algunas relaciones, que lo verifiquen por sus tablas que están elaborando

Saludos!
